<?php

namespace SuiviBundle\Repository;

/**
 * ActiviteSportifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteSportifRepository extends \Doctrine\ORM\EntityRepository
{
}
