<?php

namespace SuiviBundle\Repository;
use SuiviBundle\Entity\AimesRegimes;

/**
 * AimesRegimesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AimesRegimesRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombreLikes($regime)
    {
        $qb = $this->createQueryBuilder('l')
            ->select('count(l)')
            ->where('l.regime=:regime')
            ->setParameter(':regime', $regime);
            return $qb->getQuery()->getOneOrNullResult();
    }

    public function testLike($regime,$user)
    {
        $qb = $this->createQueryBuilder('l')
            ->select('l')
            ->where('l.regime = :regime')
            ->setParameter('regime',$regime)
            ->andWhere('l.user = :user')
            ->setParameter('user',$user);
        return $qb->getQuery()->getOneOrNullResult();
    }
    public function findLastLikes($user)
    {
        $qb= $this->createQueryBuilder('s')
            ->leftJoin('s.regime','r')
            ->where('r.nutritionniste = :user')
            ->orderBy('s.date','DESC')
            ->setParameter('user',$user);
        return $qb->getQuery()->setMaxResults(5)->getResult();


        /*$q = $this->getEntityManager()
            ->createQuery("SELECT m.regime FROM SuiviBundle:AimesRegimes m WHERE m.user =:user ORDER BY m.date DESC ")
            ->setParameter('user',$user)->setMaxResults(5);
        return $q->getResult();*/
    }
    public function findMostLikes()
    {
        $q = $this->getEntityManager()
            ->createQuery("SELECT m FROM SuiviBundle:AimesRegimes m GROUP BY m.regime ORDER BY COUNT (m)")->setMaxResults(5);
        return $q->getResult();
    }
}
