suivi:
    resource: "@SuiviBundle/Resources/config/routing.yml"
    prefix:   /

etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /admin/article

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

gu:
    resource: "@GUBundle/Resources/config/routing.yml"
    prefix:   /
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /article
kms_froala_editor_forNutri:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /
app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages